###Variables
Variables are containers that can store any values.

for example:

    rent = 1200
    gas = 202.5
    groceries = 305.6
    print(rent)
    total = rent + gas + groceries
    print(total)
 
To create a variable to store text data:

    rent = 1400
    item1 = "Rent"
    item2 = "Gas"
    item2 = "Groceries"
    print("Expense items:",item1,item2,item3)

<u>Rules for naming the variables</u>
* Pre-defined keywords cannot be used as a variable name. 
* Special characters cannot be used in the variable name. 


In [ ]:
rent = 1200
gas = 202.5
groceries = 305.6
print(rent)
total = rent + gas + groceries
print(total)

In [ ]:
rent = 1400
item1 = "Rent"
item2 = "Gas"
item3 = "Groceries"
print("Expense items:",item1,item2,item3)

###Numbers
For addition, "+" operator is used.
    
    2+4
For subtraction, "-" operator is used.

    4-2
For multiplication, "*" operator is used.

    4*2
For division, "/" operator is used.

    4/2
For remainder, "%" operator is used.

    11%2
For power, "**" operator is used.

    2**4
For example:

    pkr_ktm = 200.6
    ktm_ctw = 97.7
    total_distance = pkr_ktm + ktm_ctw
    print(total_distance)
    mph = 50 
    time = total_distance/mph
    print(time)

<u>round() fuction</u>

Syntax:

    rount(variable,decimal digits)

* Python has priorities on certain mathematical operators.
 
For example:
  10+2*3 
  
  then python first multiplies 
  
  2*3 = 6

  and then adds

  6+10 = 16 

In [ ]:
pkr_ktm = 200.6
ktm_ctw = 97.7
total_distance = pkr_ktm + ktm_ctw
print(total_distance)
mph = 50 
time = total_distance/mph
print(time)
round(time,2)

###Strings
Strings are used to store text data in python.

        text = "Hello World"

* The words of the text is stored as like of the array so 

            >>text[1]
            'e'
            >>text[0]
            'H'
            >>text[0 : 5]
            'Hello'
* We can keep either "" or '' while writing the string.
 This can be used if we have either of these in the text.

* While writing a string with multiple lines, the text should be kept 
  inside ' ' '. . .' ' '

  For example:
    
        >>text = ''' Hello Everyone.
                  My name is Sansrita. '''
          print(text)
          
          Hello Everyone
          My name is Sansrita.

* Internall it is stored as Hello Everyone \nMy name is Sansrita.
  
  It uses the \n operator which can be defined as new line.

* The '+' operator is string is used to combine two strings.

* If we need to combine a string with a number, a function str(num) is used to convert the number into a string and hence is combined using the '+' operator.

In [ ]:
text = "Hello World "
print(text)
text2 = 'Hello World 2'
print(text2)
text3 = "It's a string"
print(text3)
text4 = 'Hello "World"'
print(text4)
text5 = text + text3
print(text5)
num = 19
age = "My age is "
sen = age + str(num)
print(sen)
id = '''Hello Everyone
My name is Sansrita'''
print(id)


###Lists
Lists is used to store multiple data in same variable as a form of list.

Syntax:

        list_name = ["item1","item2","item3"]

* Lists are stored in the computer memory as an array.
<ul type="circle">
<li>item1's location is in the 0th location.
<li>item2's location is in the 1st location and so on.
</ul>

* If we want to prnt the item in the 1st location

        list_name[1]
* If we want to change the item in the 1st location

        list_name[1] = "item4"
        >>list_name
          ['item4','item2','item3']

* Similarly, as of the strings. If we want to print out a range of the elements 

        list_name[0:2]
  This prints the first 2 elements.

  To print the last element in the list we can use a negative index.

  For example:

      list_name[-1]

*  If we have to add items to our list, a method named append is used.
   
   For example:
          list_name.append = 'item1'
          >>list_name
            ['item4','item2','item3','item1']

* If we have to add the item in a certain location in the list, a method named 
insert is used.

  For example:
          
          list_name.insert(1,'item5')

  This places the 'item5' after item4 i.e.

          >>list_name
            ['item4','item5','item2','item3','item1']

* The '+' operator can be used to add two lists together.
  
  ######Note:

  ###### A list and a string/number cannot be combined together using the '+' operator.
 
* The len() function can be used to find the length of the list.

  For example:

          >>len(list_name)
            5

* 'in' operator is used to find wheather the item is in the list or not.
  
  For example:
          
          >>"item5" in list_name
            True





In [ ]:
eat = ["Pizza","MoMo","Pasta"]
drinks = ["Juice","Coke"]

#if we want to print 1st item 
print(eat[0])

#if we want to print 1st and 2nd item
print(eat[0:2])

#To print the last item
print(eat[-1])

#If we want to add Wings in the food 
eat.append("Wings")
eat

#If we want to add Chips in the 2nd position
eat.insert(1,"Chips")
eat

#If we need to combine eat and drinks
items = eat + drinks
items

print("Total number of items in the list is ",(len(items)))

#Check if Pasta is in the list or not 
"Pasta" in items

###If Statement 
If statement can be defined as a statement that checks wheather the written statement is correct or not. 

If the statement is correct then it does the process else it goes to the another statement 

Syntax:

        if statement:
          process/output
        else:
          process/output

####Operator
* '<'   Less than
* '>'   Greater than
* '<='  Less than or equal to
* '>='  Greater than or equal to
* '!='  Not equal to 
* 'and' True if both statements are corrects
* 'or'  True if any one statement is correct
* 'not' For example: 
        not 4==4
        False

In [ ]:
#Input a number from the user and identify wheather the number is even or odd
num = int(input("Enter a Number : "))
if num%2 == 0 :
  print("The number is even.")
else:
  print("The number is odd.")

###For Loop 
It is used to run the same code multiple times.

Syntax:

        if condition:
          process/output
        elif condition:
          process/output
        else:
          process/output


In [ ]:
exp = [2400, 2600, 3000, 2400, 3500, 2000, 3624, 1252, 750, 1210, 940, 450]
total = 0
for i in range(len(exp)):
    print("Month",i+1,"Expense",exp[i])
    total = total + exp[i]
print("Total expense",total)

###While loop 
It is similar to For Loop.

Syntax:

        while condition:
          process/output
          increment

In [ ]:
i = 2
while i<10 :
    print(i)
    i = i+1

###Functions
Functions are a block of code that perform a specific task.

####Defining a function 
Syntax:

        def function_name(argument):
          function body 
          return return_value
####Calling a function 
Syntax:

        function_name()
####Name arguement
Example:

        function_name(a=1,b=2)




In [ ]:
def total(exp):
  total = 0
  for item in exp:
    total = total + item
  return total

list1 = [1200,3000,4500]
list2 = [200,600,450]

list1_total = total(list1)
list2_total = total(list2)

print ("Total of List 1 : ", list1_total)
print ("Total of List 2 : ", list2_total)

###Dictionary
Dictionary allows us to store key, value pairs.

Also known as Maps, Hashtables, Associate Arrays.
Example:

        d={"apple":50, "banana": 12, "orange":25}

You can access the value by 

        d["apple"]
        50

####Adding new data in the dictionary 

        d["papaya"]=20

####Deleting the data in the dictionary

        del d["papaya"]

In [ ]:
d = {"apple":50, "banana":12, "orange":25}
for key in d:
  print("Fruit : ",key,"Quantity : ",d[key])

for k,v in d.items():
    print("Fruit : ",k,"Quantity : ",v)

####Tuples
Tuples are used to store multiple items in a single variable.

A tuple is a collection which is ordered and unchangeable.

Tuples are written with round brackets.

Tuples are immutable whereas lists are mutable.

In [ ]:
#Store your address as a tuple
#Tuples are immutable whereas lists are mutable.
address = ("Mahendrapool","Pokhara","Nepal")
print(address)


####Modules
Modules is a way of using the codes written by others. M0odules can be used for free in python.

###Importing a module.

        import module_name

###Finding functions in the module.

        dir(module_name)
###To write your own module 

        import your_file/.py

###Import from different sub directory 

        import subdirectoryname.file name

###Import from a different directory 

        sys.path.append(path)
        import filename

In [ ]:
import math
print(math.sqrt(4))
print(dir(math))

import calendar
cal = calendar.month(2016,1)
print(cal)
dir(calendar)

#import your own module
# import IfStatement 
# print(per)


####JSON
JSON : Java Script Object Notation

It is a data exchange format similar to XML.

Example:

<u>JSON</u>

    {
      "name":"Ram"
      "address":"Pokhara,Nepal"
    }

<u>XML</u>

    <name> Ram </name>
    <address> Pokhara,Nepal </address>

* JSON is much more light weighted than XML



In [ ]:
# #writing record as a json format
# book = {}
# book['Ram'] = {
#     'Name' : 'Ram',
#     'Address' : 'Pokhara, Nepal'
# }
# book['Hari'] = {
#     'Name' : 'Hari',
#     'Address' : 'Jumla, Nepal'
# }

# import json
# s=json.dumps(book)
# with open ("/home/sansrita/Desktop/Python/address.txt","w") as f:
#     f.write(s)

# #printing the record from the .txt file
# f=open("/home/sansrita/Desktop/Python/address.txt","r")  
# s= f.read()
# print(s)
# print(type(s))
# import json
# l= json.loads(s)
# print(l)
# print(type(l))
# print(l['Hari'])
# print(l['Hari']['Address'])

# #print all the record
# for person in l:
#     print(l[person])

####Reading/Writing Files

* open() opens a file for reading or writing

        open("file_name_and_path" , "file_open_mode")

###File open modes
* w : overwrites in the file
* a : appends the text into the file
* r : reads from the file
* r+ : opens file for both reading and writing
* w+ : opens file for both reading and writing. If the file doesn't exist then a new file is created. If it exists then it will overwrite it.

###Writing

* f.write("text_to_write") : writes in the file
* f.close() : closes the file.

###Reading
* f.read() : Reads the file
* f.close()

####if __ name__ =="__ main__"
* __ name __ is a pre-defined variable in python which gets set to main. 
* The .py in which the if __ name__ =="__ main__" is written is set to the main. 
* Can be compared with main function in C++.
* If the code is run from another .py then the value of __ name __ is main.
* But if it is run from the ,py then the value of __ name __ is the file itself.


####Exception Handling
Exceptions are errors detected at the time of program execution.

Example:

        x = input("Enter first number : ")
        y = input("Enter second number : ")
        try:                                    #exception handling
            z = int(x)/int(y)
        except Exception as e:
            print("Exception occured: ",e)
            z = None
        print("Division is: ",z)

In this example, we are setting a exception as e to find out which exception will occur. But if we already have an idea about which exception is going to occur we can set it as such.

For example:

In the above example, we can replace 'Exception' as 'ZeroDevisionError'.

###Finding the type of exception

        type(exception).__name__
        

In [ ]:
x = input("Enter first number : ")
y = input("Enter second number : ")
try:                                    #exception handling
    z = int(x)/int(y)
except Exception as e:                  
    print("Exception occured: ",e)
    print("Exception Type: ",type(e).__name__)    #finding exception name
    z = None
# except ZeroDivisionError as e:                  
#     print("Zero Devision Exception occured")
#     z = None
print("Division is: ",z)

####Class and Objects

###Class
* The propertities and methods form a central entity called class.
* And abstraction of the entities that consists of common set of properties and methods.

###Objects
* A specific instance of a class.



In [ ]:
class Human:
    def __init__(self, n, o):
    #properties of class Human
        self.name = n               
        self.occupation = o 
    #Methods of class Human
    def do_work(self):
        if self.occupation == "tennis player":
            print(self.name,"plays tennis.")
        elif self.occupation == "actor":
            print(self.name,"acts on films.")
    def speaks(self):
        print(self.name,"says how are you?")
    
tom = Human("Tom Cruise","actor")
tom.do_work()
tom.speaks()

john = Human("John Isner","tennis player")
john.do_work()
john.speaks()

####Inheritance
* Inheritance can be used for inheriting the properties of a class to its derived class.

Syntax:
    
    class class_name:
      #class_name body

    class derived_class_name(class_name):
      #deriverd_class_name body

###Benifits of Inheritance 
* The codes of the class can be reused and modified in the derived class
* Readability 
* Extensibility

###Multiple Inhoeritance

Syntax:
    
    class A:
      #body of A
    
    class B:
      #body of B

    #derived class from A and B
    class C(A,B):
      #body of C 

####Raise Exception

Syntax:

    try:
      raise exception_name("exception type")
    except exception:
      body

###User defined Exception

    class exception_name(exception):
      body

####Finally

* The code in finally block will always execute no matter what.

In [ ]:
def process_file():
    try:
        f = ("/home/sansrita/Desktop/Python/text.txt")
        x = 1/0
    except FileNotFoundError  as e:
        print("Inside Except")
    #code in finally block will excecute no matter what.
    finally:
        print("cleaning up file")
        f.close()
process_file()

####Iterators

    a= ["hey","how","are","you"]
    for i in a:
      print (i)

* While we're using for loop, the code uses the iter method from the list and the next method is used to print the data from the list.

Syntax for iter and next:

      >>next(iter(a))
        hey
* We have a reversed method that takes the data from the last and them to first while calling the next method.

    
      >>next(reversed(a))
        you

In [ ]:
class name():
    def __init__(self):
        self.name = ["Ram","Shyam","Sita","Gita"]
        self.index = -1
    
    def __iter__(self):
        return self
    
    def __next__(self):
        self.index += 1
        if self.index == len(self.name):
            raise StopIteration
        
        return self.name[self.index]

n = name()
itr = iter(n)
print(next(itr))
print(next(itr))
print(next(itr))
print(next(itr))
print(next(itr))


####Generators
* Generators is simply a way of creating iterators. 
* Generators can be defined by using yeild statement in the function instead of return.
* yeild statement is similar to return statement but not same.

###Benefits of using Generators over class based Iterators
* Don't need to define iter() and next() methods.
* Don't need to raise StopIteration exception.

In [ ]:
from re import A


def fib():
    a,b = 0,1
    while True:
        yield a
        a,b = b, a+b
    
for f in fib():
    if f>100:
        break
    print(f)

####List Comprehension
* List comprehension provides a way to transform one list to another.

      
      

In [ ]:
#making a list of even numbers from the numbers list
numbers = [1,2,3,4,5,6,7]
even = [i for i in numbers if i%2 == 0]
print(even)

####Set Comprehension
* Set is an unordered list of unique items.

###Defining a set 
    s = set([list])
* Removes repeated numbers from the set.




In [ ]:
#making a list of even numbers from the numbers list
s = set([1,2,3,4,5,6,7])
even = {i for i in s if i%2 == 0}
print(even)

####Dict Comprehension
* The zip() is used to combine two lists into a dictionary.


In [ ]:
cities = ["Pokhara","Delhi","New York"]
countries = ["Nepal","India","USA"]
z = zip(cities,countries)
for a in z:
  print (a)

d = {cities:countries for cities,countries in zip(cities,countries)}
print (d)

('Pokhara', 'Nepal')
('Delhi', 'India')
('New York', 'USA')
{'Pokhara': 'Nepal', 'Delhi': 'India', 'New York': 'USA'}


####Sets 
* Sets is an unordered collection of unique elements.
Syntax:
    
      set_name = {items}
      
      a = set()
      a.add(item_name)

* Empty set is considered as dictionary.

      set_name = {} #is a dictionary

* Set removes every repeated numbers fromm the dictionary.

      uniqueset = set (list)

####Frozen Sets 
* Frozen sets are the sets where the contents cannot be changed.
* Frozen sets and sets are same but frozen sets doesn't allow to add new elements to the set.
 
###Initializing frozen set 

    fs = frozenset(list)


* Frozen sets and sets support iterators.


In [ ]:
x = {"a","b","c"}
print("a" in x)
print("d" in x)
for i in x:
  print(x)
y = {"a","g","h"}
z= {"a","g"}

#for union of x and y 
print (x|y)

#for intersection of x and y 
print(x&y)

#for subtraction of x and y 
print(x-y)

#for subset (if x is subset of y)
print(x<y)

#if z is subset of y 
print(z<y)

True
False
{'a', 'c', 'b'}
{'a', 'c', 'b'}
{'a', 'c', 'b'}
{'b', 'h', 'g', 'c', 'a'}
{'a'}
{'c', 'b'}
False
True


####Command line argument processing using argparse
* There are two types of arguments that argparse module supports:
  * Positional 
  * Optional

* Optional argument will work even if all the arguments are not passed.


In [ ]:
#Program to input two numbers and a operation to be used and return the result of operation based on inputs
#Posional argument 
import argparse
if __name__== "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("number1", help ="first number")
    parser.add_argument("number2", help ="second number")
    parser.add_argument("operation", help ="operation")

    args = parser.parse_args()
    print(args.number1)
    print(args.number2)
    print(args.operation)

    n1 = int(args.number1)
    n2 = int(args.number2)
    result = None
    
    if args.operation == "add":
        result = n1+n2
    elif args.operation == "subtract":
        result = n1-n2
    elif args.operation == "multiply":
        result = n1*n2

    print(result)

In [ ]:
#for optional argument add --to arguments  
import argparse
if __name__== "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--number1", help ="first number")
    parser.add_argument("--number2", help ="second number")
    parser.add_argument("--operation", help ="operation", choices = ["add","subtract","multiply"])

    args = parser.parse_args()
    print(args.number1)
    print(args.number2)
    print(args.operation)

    n1 = int(args.number1)
    n2 = int(args.number2)
    result = None
    
    if args.operation == "add":
        result = n1+n2
    elif args.operation == "subtract":
        result = n1-n2
    elif args.operation == "multiply":
        result = n1*n2

    print("Result : ", result)

####Decorators
* Decorators allows us to wrap a function into another function.


In [ ]:
#To find time taken in a function without decorators
import time 

def calc_square(numbers):
  start = time.time()
  result = []
  for number in numbers:
    result.append(number*number) 
    end = time.time()
    print ("calc_square took " +str((end-start)*1000) + "mil sec")
    return result

def calc_cube(numbers):
  start = time.time()
  result = []
  for number in numbers:
    result.append(number*number*number) 
    end = time.time()
    print ("calc_cube took " +str((end-start)*1000) + "mil sec")
    return result
    
array = range(1,100000)
out_square = calc_square(array)
out_cube = calc_cube(array)

calc_square took 0.0011920928955078125mil sec
calc_cube took 0.00095367431640625mil sec


* Functions are first class objects in python. You can use functions as any other variable, you can pass them as argument to another function or even return them as a return value.

In [ ]:
#To find time taken in a function using decorators
import time 

def time_it(func):
  def wrapper(*args, **kwargs):
    start =time.time()
    result = func(*args,*kwargs)
    end = time.time()
    print(func.__name__ + " took "+str((end-start)*1000) +"mili seconds")
  return wrapper

@time_it
def calc_square(numbers):
  result = []
  for number in numbers:
    result.append(number*number) 
    return result

@time_it
def calc_cube(numbers):
  result = []
  for number in numbers:
    result.append(number*number*number)
    return result

array = range(1,100000)
out_square = calc_square(array)
out_cube = calc_cube(array)

calc_square took 0.003337860107421875mili seconds
calc_cube took 0.0035762786865234375mili seconds


####Multithreading
* Doing multiple tasks at the same time in a program is called multithreading in the program.

Example:

In [ ]:
#For a given list of numbers print square and cube of every numbers(without using multithreading)
import time

def calc_square(numbers):
  for n in numbers:
    time.sleep(0.2)
    print("Square : ",n*n)
    
def calc_cube(numbers):
  for n in numbers:
    time.sleep(0.2)
    print("Cube : ",n*n*n)

arr = [2,3,8,9]

t = time.time()
calc_square(arr)
calc_cube(arr)

print("Time taken : ",time.time()-t)

Square :  4
Square :  9
Square :  64
Square :  81
Cube :  8
Cube :  27
Cube :  512
Cube :  729
Time taken :  1.6067488193511963


In [ ]:
#For a given list of numbers print square and cube of every numbers(using multithreading)
import time
import threading

def calc_square(numbers):
  for n in numbers:
    time.sleep(0.2)
    print("Square : ",n*n)
    
def calc_cube(numbers):
  for n in numbers:
   time.sleep(0.2)
  print("Cube : ",n*n*n)

arr = [2,3,8,9]

t = time.time()

t1 = threading.Thread(target=calc_square,args=(arr,))
t2 = threading.Thread(target=calc_cube,args=(arr,))

t1.start()
t2.start()

t1.join()
t2.join()

print("Time taken : ",time.time()-t)

Square :  4
Square :  9
Square :  64
Square :  81
Cube :  729
Time taken :  0.8072023391723633


####Multiprocessing
* In multi[rocessing, the result is only valid within the function but not outside.

In [ ]:
import multiprocessing

square_result = []

def calc_square(numbers):
  global square_result
  for n in numbers:
    print("square: ",str(n*n))
    square_result.append(n*n)
  print("Within the process : Result : " + str(square_result))

def calc_cube(numbers):
  for n in numbers:
    print("cube: ",str(n*n*n))
      
if __name__ == "__main__":
  arr = [2,3,8,9]
  p1 = multiprocessing.Process(target = calc_square , args = (arr,))
  p2 = multiprocessing.Process(target = calc_cube , args = (arr,))
  
  p1.start()
  p2.start()

  p1.join()
  p2.join()

print("Outside the process : Result : " + str(square_result))

square:  4
square:  9
square:  64
square:  81
Within the process : Result : [4, 9, 64, 81]
cube:  8
cube:  27
cube:  512
cube:  729
Outside the process : Result : []


* Sharing of data between processes using array

In [ ]:
import multiprocessing
import numbers

def calc_square(numbers,result):
    for idx, n in enumerate(numbers):
        result[idx] = n*n
       
if __name__ == "__main__":
  numbers = [2,3,8,9]
  result = multiprocessing.Array('i',4)
  p1 = multiprocessing.Process(target = calc_square , args = (numbers, result))

  p1.start()
  p1.join()
  
  print(result[:])

* Sharing of data between processes using multiprocessing queue

In [ ]:
import multiprocessing

def calc_square(numbers,q):
    for n in numbers:
        q.put(n*n)

if __name__ == "__main__":
    numbers = [2,3,5]
    q = multiprocessing.Queue()
    p = multiprocessing.Process(target=calc_square, args=(numbers,q))

    p.start()
    p.join()

    while q.empty() is False:
        print(q.get())

In the above program,
* q.put() : puts the data in the queue.
* q.empty() : checks if the queue is empty or not.
* q.get() : gets the data from the queue.

Queue is the type of data structure where the first in gets first out.

**Difference between multiprocessing queue and queue module.**
* Multiprocessing Queue
  * Syntax:
        import multiprocessing 
        q = multiprocessing.Queue()
  * Lives in shared memory 
  * Used to share data between processes.

* Queue Module
  * Syntax:
        import queue 
        q = queue.Queue()
  * Lives in in-process memory.
  * Used to share data between threads.
  

**Lock**
* Why do we need lock?

  When two Processes or Threads has the same shared resource, then to maintain the privacy lock is needed.
 
* What will happen if we don't use lock?

  The code might give wrong outputs.



In [ ]:
import time
import multiprocessing 

def deposit(balance, lock):
  for i in range(100):
    time.sleep(0.1)
    lock.acquire()
    balance.value = balance.value + 1
    lock.release()

def withdraw(balance, lock):
  for i in range(100):
    time.sleep(0.1)
    lock.acquire()
    balance.value = balance.value - 1
    lock.release()

if __name__ == "__main__":
  balance = multiprocessing.Value("i", 200)
  lock = multiprocessing.Lock()
  d = multiprocessing.Process(target = deposit, args = (balance,lock))
  w = multiprocessing.Process(target = withdraw, args = (balance,lock))
  d.start()
  w.start()
  d.join()
  w.join()
  print(balance.value)

200


####Multiprocessing Pool
* It is simply dividing the process in the code to different parts for different processing units and again later combining them into the same.

In [ ]:
from multiprocessing import Pool

def f(n):
    return n*n

if __name__ == "__main__":
    array = [1,2,3,4,5]
    p = Pool()
    result = p.map(f,array)
    print(result)

* p.map(f,array) : divides the process of the function f for array into different unitx.
* Using pool will speed up the time of execution as it divides the process.
* Pool(processes= n) : creates n processs. 

####Python Testing Units 
* Python testing frameworks:
  * unittest
  * nose
  * pytest


###Steps for testing a code in pytest
* Make a python file with prifix test and import the file you want to test.
* Keep prifix "test" in every module.
* To set the answer "assert" is used.
* Run the code in terminal.
  * python3 -m pytest test_filename.py
  * py.test test_filename.py
  * py.test -v test_filename.py : for detailed output

####Skip Testing
* A decorator of the pytest module is used to skip the testing of a certain portion of the code.

      import pytest
      @pytest.mark.skip(reason = "...")

  * If there is some condition,

        @pytest.mark.skipif(condition,reason = "...")
  
  * To run the test with certain word,
  
        #run the in terminal 
        pytest -k word

####Custom Markers
* Decorator of pytest module is used to mark the certain portion of code as some name.

      import pytest
      @pytest.mark.name

  * To run the code with certain names only,

        #run in the terminal
        pytest -m name

  * To run the code with name other than the given,

        #run in the terminal
        pytest -m "not name"

####numpy 
* numpy's most useful feature is n dimentional array objects 

###Benifits of numpy array over python list 
* Less Memory 
* Fast 
* Convinient

###Basic array operations
      import numpy as np
* For one dimentional array,
      b = np.array[(1,2)]
* For two dimentional array,
      a = np.array[(1,2),(2,3)]
* Find dimention of the array,
      a.ndim
      >> 2 
* Find byte size of the array,
      a.itemsize
      >> 4
* Find current datatype of the array,
      a.dtype
* Change datatype of the array,
      a = np.array[(1,2),(2,3), dtype = np.float64]
    * can be changed to complex number as well
* Finding total number of elements,
      a.size
      >>4
* Finding the order of the array
      a.shape
      >> (2,2)
* For elements with all 0s or 1s ,
      np.zeros((2,2))
      np.ones((2,2))
* Array of range of numbers,
      np.arange(1,5)
      >>array[(1,2,3,4)]
      np.arange(1,5,2)
      >>array[(1,3)]
* To make a range of array linearly spaced,
      np.linspace(1,4,4)
      >>array([1., 2., 3., 4.])
* To reshape an array,
      a.reshape(rows,columns)
* To make n-dimentional array into one dimentional array,
      a.ravel()
    * will not alter your original array
* Max and min values of the array,
      a.max()
      a.min()
* Sum of the array,
  * All the elements,
        a.sum()
  * Sum of the elements in each column,
        a.sum(axis = 0)
  * Sum of the elements in each row,
        a.sum(axis = 1)
* Square root of the array,
      np.sqrt(a)
* Standard Deviation of the array,
      np.std(a)


###Indexing and Slicing
      

In [10]:
import numpy as np 
a = np.array([(1,2,3),
             (4,5,6),
             (7,8,9)])

#prints the first two elements from the first row
print(a[0,0:2])

#prints all the elements from the first row
print(a[0,0:3])
print(a[0,:])

#prints the last two elements from the first row
print(a[0,1:3])

#prints all the elements from the first column
print(a[0:3,0])
print(a[:,0])

#prints the last row
print(a[2,:])
print(a[-1])

[1 2]
[1 2 3]
[1 2 3]
[2 3]
[1 4 7]
[1 4 7]
[7 8 9]
[7 8 9]


###Iterate through arrays


In [12]:
import numpy as np 
a = np.array([(1,2,3),
             (4,5,6),
             (7,8,9)])

#prints the rows in the array 
for rows in a:
  print(rows) 

#makes the array one dimensional and iterates through each cell
for cell in a.flat:
  print(cell)



[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


###Sticking two arrays together

In [19]:
import numpy as np
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

#stacks the two arrays vertically
print(np.vstack((a,b)),"\n")

#stacks the two arrays horizontally
print(np.hstack((a,b)),"\n")

c = np.arange(30).reshape(2,15)

#splits the array horizontally 
result = np.hsplit(c,3)
print(result[0],"\n")
print(result[1],"\n")
print(result[2],"\n")

#To spit the array vertically 
result = np.vsplit(c,2)
print(result[0],"\n")
print(result[1],"\n")

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]] 

[[ 0  1  2  3  4]
 [15 16 17 18 19]] 

[[ 5  6  7  8  9]
 [20 21 22 23 24]] 

[[10 11 12 13 14]
 [25 26 27 28 29]] 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]] 

[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 



###Indexing with boolean array

In [26]:
import numpy as np 
a = np.arange(10).reshape(2,5)
b = a > 5

print(a,"\n")
print(b,"\n")

#prints only the elements greater than 5
print(a[b],"\n")

#Replaces all the elements greater than 5 to 1
a[b] = 1
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[False False False False False]
 [False  True  True  True  True]] 

[6 7 8 9] 

[[0 1 2 3 4]
 [5 1 1 1 1]]


###Iterate numpy array using nditer

In [34]:
import numpy as np 
a = np.array([(1,2,3),
             (4,5,6),
             (7,8,9)])

#print the elements using flatten
for cell in a.flatten():
  print(cell)
print("\n") 

#print the elements using nditer
for x in np.nditer(a , order = "C"):
  print(x)
print("\n")

for x in np.nditer(a , order = "F"):
  print(x)
print("\n")

#print the entire column in one iteration
for x in np.nditer(a , order = "F",flags = ["external_loop"]):
  print(x)
print("\n")

#op_flags on for loop
for x in np.nditer(a , op_flags = ["readwrite"]):
  x[...] = x*x
print(a,"\n")


1
2
3
4
5
6
7
8
9


1
2
3
4
5
6
7
8
9


1
4
7
2
5
8
3
6
9


[1 4 7]
[2 5 8]
[3 6 9]


[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 



* Iterating through two arrays :
  * There shape should be same. 
  * One of the dimensions in one of the arrays should be same.

In [39]:
import numpy as np 
a = np.arange(6).reshape(3,2)
b = np.arange(6,9).reshape(3,1)

for x,y in np.nditer([a,b]):
  print(x,y)

0 6
1 6
2 7
3 7
4 8
5 8
